language: python
cache: pip

jobs:
  include:
    - dist: trusty
      addons:
        mariadb: 10.3
    - dist: trusty
      addons:
        mariadb: 10.4
    - dist: xenial
      addons:
        mariadb: 10.3
    - dist: xenial
      addons:
        mariadb: 10.4
    - dist: bionic
      addons:
        mariadb: 10.3
    - dist: bionic
      addons:
        mariadb: 10.4

install:
  - mysql --version
  - mysql -e "SET Password=PASSWORD('travis')"
  - MYSQL_CMD="mysql -u root --password=travis -e"

  - $MYSQL_CMD "SET GLOBAL character_set_server = 'utf8mb4'"
  - $MYSQL_CMD "SET GLOBAL collation_server = 'utf8mb4_unicode_ci'"

  - $MYSQL_CMD "CREATE DATABASE test_frappe"
  - $MYSQL_CMD "CREATE USER 'test_frappe'@'localhost' IDENTIFIED BY 'test_frappe'"
  - $MYSQL_CMD "GRANT ALL PRIVILEGES ON \`test_frappe\`.* TO 'test_frappe'@'localhost'"

  - $MYSQL_CMD "SET Password=PASSWORD('travis')"
  - $MYSQL_CMD "FLUSH PRIVILEGES"

script: mysql --version
