dist:
  - trusty
  - xenial
  - bionic
language: python
cache: pip

jobs:
  include:
    addons:
      mariadb: 10.3
    addons:
      mariadb: 10.4

install:
  - mysql -u root -e "SET GLOBAL character_set_server = 'utf8mb4'"
  - mysql -u root -e "SET GLOBAL collation_server = 'utf8mb4_unicode_ci'"

  - mysql -u root -e "CREATE DATABASE test_frappe"
  - mysql -u root -e "CREATE USER 'test_frappe'@'localhost' IDENTIFIED BY 'test_frappe'"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON \`test_frappe\`.* TO 'test_frappe'@'localhost'"

  #- mysql -u root -e "UPDATE mysql.global_priv SET Password=PASSWORD('travis') WHERE User='root'"
  - mysql -u root -e "SET Password=PASSWORD('travis') WHERE User='root'"
  - mysql -u root -e "FLUSH PRIVILEGES"
